### ISSUE TITLE
[Improvement] Selection works only if element is fully inside selection area

### ISSUE THREAD

**Issue by giovannigiordano** [excalidraw/excalibur#33]
As the title says, the selection of elements works only when the elements are fully inside the selection area.
It should work even if there is only an intersection between the selection area and the elemen.

**Comment by vjeux** [comment]
This is actually intentional. I find it annoying on other drawing apps to select a few elements inside of a box. Whenever you start selecting anything you also select the box.

This is unconventional but I think it’s better for this use case.

Maybe there are other ways to workaround this issue
