### ISSUE TITLE
[TODO] Path-dependent hit testing

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalibur#9]
For lines (arrow, circle, rectangles), we should only hit test when you are within X pixels of the line and not everywhere in the whitespace

**Comment by nanot1m** [comment]
Is it good idea to create multiple factories for each element type?
Every factory can define its own hit test function and draw function. Text element factory can define `font`, `text` and `measure` properties.

**Comment by vjeux** [comment]
Sounds like a good idea yeah!
